# Generated by Django 2.1.1 on 2018-10-22 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='title',
            new_name='event_title',
        ),
    ]
